omniauth:
  google_oauth2:
    key: <%= ENV['GOOGLE_OAUTH_KEY'] %>
    secret: <%= ENV['GOOGLE_OAUTH_SECRET'] %>
  github:
    key: <%= ENV['GITHUB_OAUTH_KEY'] %>
    secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
  twitter:
    key: <%= ENV['TWITTER_OAUTH_KEY'] %>
    secret: <%= ENV['TWITTER_OAUTH_SECRET'] %>